project/__init__.py
from flask import Flask, session, jsonify, redirect, url_for, escape, render_template, request, flash

app = Flask(__name__)

from project.csv_data.routes import mod
from project.site.routes import mod
from project.scraping.routes import mod

app.register_blueprint(site.routes.mod)
app.register_blueprint(csv_data.routes.mod)
app.register_blueprint(scraping.routes.mod)

project/csv_data/routes.py
from flask import Blueprint, Flask, session, jsonify, redirect, url_for, escape, render_template, request, flash
from project.csv_data.data import * 
#from project.csv_data.graph2 import *
import numpy as np
import pandas as pd
import os 


mod = Blueprint('csv_data', __name__,template_folder='templates', static_folder='static',
                                                static_url_path='/static')

@mod.route('/csv_home')
def homepage():
    #Creating ojects
    data = Data()

    csv_data_file = os.path.join(mod.root_path, 'data/Video_Games_Sales.csv')
    game_data = pd.read_csv(csv_data_file)
    
    score_sales_correlation = data.correlation_globalSales_criticScore(game_data)
    score_sales_correlation_US = data.correlation_USSales_criticScore(game_data)
    mean_game_rating = data.average_game_rating(game_data)
    return render_template('csv_data/csv_index.html', score_sales_correlation = score_sales_correlation, 
        mean_game_rating = mean_game_rating, score_sales_correlation_US = score_sales_correlation_US)


########## AJAX Functions below this line #################

#This route will deal with getting the max rating of a video game by year and genre 
@mod.route('/_by_max_rating')
def by_max_rating():
    year = request.args.get('year', 0, type=int)
    genre = request.args.get('genre', 0, type=str)
    #Creating a data object to interact with the data class which 
    #handles the data. 
    data = Data() 
    csv_data_file = os.path.join(mod.root_path, 'data/Video_Games_Sales.csv')
    game_data = pd.read_csv(csv_data_file)
    game_title = data.get_rating_based_year_genre(game_data, year, genre)
    return jsonify(result = game_title)

#This route will deal with getting the max earnings of a video game by genre 
@mod.route('/_by_max_earnings')
def by_max_earning():
    genre = request.args.get('genre', 0, type=str)
    data = Data()
    csv_data_file = os.path.join(mod.root_path, 'data/Video_Games_Sales.csv')
    game_data = pd.read_csv(csv_data_file)
    game_title_max_earnings = data.get_earnings_based_genre(game_data, genre)
    return  jsonify(result = game_title_max_earnings)


@mod.route('/_by_game_title')
def by_title():
    csv_data_file = os.path.join(mod.root_path, 'data/Video_Games_Sales.csv')
    game_data = pd.read_csv(csv_data_file)
    gameTitle = request.args.get('genre', 0, type=str)
    data = Data()
    critic_score = data.get_critic_score_of_game(game_data, gameTitle)
    return  jsonify(result = critic_score)

project/scraping/routes.py
from flask import Blueprint, Flask, session, jsonify, redirect, url_for, escape, render_template, request, flash
import json 
from project.scraping.scraping import *
from project.scraping.fixInput import *

mod = Blueprint('scraping', __name__, template_folder='templates', static_folder='static',
                                                static_url_path='/static')

@mod.route('/scraping_home', methods=['GET', 'POST'])
def scraping_homepage():
    if request.method == 'POST':
        #Creating the objects that I'll use in this route
        fix_String = Fix_Input()
        scrape = Web_Scraping()
        #Recieving the information from the user.
        gameTitle = request.form['gameTitle']
        gameSystem = request.form['system']

        game_Title = gameTitle 

        gameTitle = fix_String.transform_user_input_to_lowercase(gameTitle)
        gameTitle = fix_String.add_dash_in_gameTitle(gameTitle)

        review_grades = scrape.get_data_based_on_game_title(gameTitle, gameSystem)

        if review_grades == 'No Data Found!':
            score_mean_formatted = review_grades
            score_median_formatted = review_grades
            score_std_formatted = review_grades
        else:
            score_dataFrame = scrape.convert_list_to_series(review_grades)
            score_mean_formatted = scrape.calculate_mean(score_dataFrame)
            score_std_formatted = scrape.calculate_standard_deviation(score_dataFrame)
            score_median_formatted = scrape.calculate_median(score_dataFrame)
        return render_template('scraping/scraping.html', mean = json.dumps(score_mean_formatted), 
            std = json.dumps(score_std_formatted), scores = json.dumps(review_grades), game_title = game_Title,
            median = json.dumps(score_median_formatted))
    return render_template('scraping/scraping.html')

project/site/routes.py
from flask import Blueprint, render_template

mod = Blueprint('site', __name__,template_folder='templates', static_folder='static',
                                                static_url_path='/static')

@mod.route('/')
def homepage():
  return render_template('site/index.html')

@mod.route('/home')
def home():
    return render_template('site/home.html')

project/templates/base.html
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta charset='utf-8'>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

  <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css?family=Gaegu" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Chela+One" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/base.css') }}">
              <link href = "https://code.jquery.com/ui/1.10.4/themes/ui-lightness/jquery-ui.css"
         rel = "stylesheet">
          <script src = "https://code.jquery.com/jquery-1.10.2.js"></script>
      <script src = "https://code.jquery.com/ui/1.10.4/jquery-ui.js"></script>
    <script type="text/javascript">
        var $SCRIPT_ROOT = {{ request.script_root|tojson|safe }};
    </script>
  <title>Game Ratings</title>
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <a class="navbar-brand" href="{{ url_for('site.homepage') }}">Game Ratings</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link font" href="{{ url_for('csv_data.homepage') }}">CSV Data</a>
      </li>
      <li class="nav-item">
        <a class="nav-link font" href="{{ url_for('scraping.scraping_homepage') }}">Web Scraping</a>
      </li>
    </ul>
  </div>
</nav>

<!-- <nav role='navigation'>
  <ul>
    <li><a href="{{ url_for('site.home') }}">Home</a></li>&nbsp;&nbsp;&nbsp;
    <li><a href="{{ url_for('csv_data.homepage') }}">CSV Data</a></li>&nbsp;&nbsp;&nbsp;
    <li><a href="{{ url_for('scraping.scraping_homepage') }}">Web Scraping Data</a></li>
  </ul>
</nav> -->

{% block content %}


{% endblock %}

<footer role="contentinfo">

  <div class='footer_div'>
     <h5 class='font'>Copyright &copy; 2018 Mike Cuddy Productions<br></h5>
  </div>
  <div>
    <a href="https://www.linkedin.com/in/mcuddy1/"><i class="fa fa-linkedin-square fa-3x" aria-hidden="true"></i></a>
    <a href="https://twitter.com/mcuddy7"><i class="fa fa-twitter-square fa-3x" aria-hidden="true"></i></a>
    <a href="https://codingsaga.wordpress.com/"><i class="fa fa-pencil fa-3x" aria-hidden="true"></i></a>
    <a href="https://github.com/ravenusmc"><i class="fa fa-github-square fa-3x" aria-hidden="true"></i></a>
  </div>

</footer>

</body>
</html>